#!/bin/bash
NEWLINE=$'\n'
SPACE=$' '
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
DEFAULT=$(tput setaf 9)
BOLD=$(tput bold)
CLEAR=$(tput sgr0)

export VIRTUAL_ENV_DISABLE_PROMPT=1

virtualenv_info(){
	local VENV
	# Get Virtual Env
	if [[ -n "$VIRTUAL_ENV" ]]; then
		# Strip out the path and just leave the env name
		VENV="${VIRTUAL_ENV##*/}"
	else
        # In case you don't have one activated
        VENV=''
	fi
	
	[[ -n "$VENV" ]] && echo "${MAGENTA}($VENV)${SPACE}"
}

leading_newline() {
	if [ "$(current_row)" != "0" ]; then echo "${NEWLINE} ";
	else echo " "
	fi
}

git_branch() {
	local RESULT
	local SUCCESS=0
	local BRANCH
	local MAX_NAME_LENGTH=10
	git symbolic-ref --short HEAD &> /dev/null; RESULT=$?
	if [ $RESULT == $SUCCESS ]; then
		BRANCH="$(git symbolic-ref --short HEAD)"
	fi

	if [ ${#BRANCH} -gt $MAX_NAME_LENGTH ]; then
		BRANCH=${BRANCH::MAX_NAME_LENGTH}"..."
	fi

	if [ $BRANCH ]; then
		echo ${GREEN}\(${BRANCH}\)${SPACE}${DEFAULT}
	fi
}


start_prompt() {
	exec < /dev/tty
	oldstty=$(stty -g)
	stty raw -echo min 0
	# on my system, the following line can be replaced by the line below it
	echo -en "\033[6n" > /dev/tty
	# tput u7 > /dev/tty    # when TERM=xterm (and relatives)
	IFS=';' read -r -d R -a pos
	stty $oldstty
	# change from one-based to zero based so they work with: tput cup $row $col
	row=$((${pos[0]:2} - 1))
	if [ $row == 0 ]; then
		echo "${BOLD}"
	else
		echo "${NEWLINE}${BOLD}"
	fi
}

# export PS1="\$(make_prompt)"
#export PS1="$(tput bold)\$(leading_newline)$(tput bold)$(tput setaf 4)\u:$(tput setaf 2)\w$(tput setaf 9): (\j jobs)\n$(tput setaf 6)\! $(tput setaf 4)\$(include_git_branch)\$: $(tput sgr0)"
export PS1=\
"\$(start_prompt)"\
"${CYAN}\! "\
"${BLUE}\u"\
"${YELLOW}@"\
"${BLUE}\h$"\
"${YELLOW}:"\
"${GREEN}\w"\
"\$( [ \j -gt 0 ] && echo \"${DEFAULT} | \j jobs\" )"\
"\n\$(git_branch)"\
"\$(virtualenv_info)"\
"${DEFAULT}\$${SPACE}"\
"${CLEAR}"

# "$( [ ! $(current_row) ] && echo $'\n')"\
